version: '1.0.0-sr{build}-test'
configuration: Release


branches:
  only:
    - master-test


assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'


before_build:
  - nuget restore


after_build:
  - ps: Write-Host $env:appveyor_build_version
  - ps: '& ".\NuGet Package Specifications\NuGet Deployment.ps1" -Version $env:appveyor_build_version -NuGet "C:\Tools\NuGet\nuget.exe"'


artifacts:
  - path: '**\*.nupkg'


# build NuGet package and upload it to artifacts
build:
  parallel: true
  verbosity: minimal
  publish_nuget: true

cache:
  - packages -> **\packages.config

deploy:
  provider: NuGet
  api_key:
    secure: jfcUvHZhgnUboplqTBDWr8mG5PIlrgBv5TA2fhhop4ZSiDxskyy+RtYyeHoduJFR